# node <id> <host> <kv_port> <repl_port>
node node1 127.0.0.1 5500 5600
node node2 127.0.0.1 5501 5601

# tablet <tablet_id> <row_start> <row_end> <replica1> <replica2> ...
tablet tablet0 "" "" node1 node2
