# node <id> <host> <kv_port> <repl_port>
node node1 127.0.0.1 6500 6600
node node2 127.0.0.1 6501 6601
node node3 127.0.0.1 6502 6602

# tablet <tablet_id> <row_start> <row_end> <replica1> <replica2> <replica3>
tablet tabletA a g node1 node2 node3
tablet tabletB h p node2 node3 node1
tablet tabletC q zzzzz node3 node1 node2
